# Generated by Django 4.2 on 2025-03-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_app', '0002_auto_20200926_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfood',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calories_app.profile'),
        ),
    ]
